import { formatLapTime, formatMoves } from './engine/scoreFormat';

// Shared game catalog — one source of truth for the home page grid and the
// Help page, so a new game (or a controls change) only needs updating here.
export const GAMES = [
  {
    id: 'snake',
    title: 'Snake',
    emoji: '🐍',
    tag: 'Play now',
    path: '/games/snake',
    blurb: "The classic. Eat, grow, and don't bite yourself.",
    goal: 'Eat food to grow longer and rack up points. It\'s over if you hit a wall or your own tail.',
    controls: 'D-pad / left stick / arrow keys / WASD to move',
  },
  {
    id: 'racer',
    title: 'Drift Racer',
    emoji: '🏎️',
    tag: 'Play now',
    path: '/games/drift-racer',
    blurb: 'Top-down laps, drifting, and boost. Built for triggers.',
    goal: 'Race laps around the ring track as fast as you can — hold your line through the corners.',
    controls: 'R2/L2 or Up/Down or left stick to accelerate/brake · Left/Right or stick to steer',
    // Lower lap time is the better result — see Leaderboard's `ascending` prop.
    rankAscending: true,
    format: formatLapTime,
  },
  {
    id: 'chomper',
    title: 'Maze Chomper',
    emoji: '👾',
    tag: 'Play now',
    path: '/games/maze-chomper',
    blurb: 'Eat every dot. Dodge every ghost.',
    goal: 'Clear every dot in the maze while dodging ghosts. Grab a big dot to turn the tables and hunt them instead.',
    controls: 'D-pad / left stick / arrow keys / WASD to move',
  },
  {
    id: 'shooter',
    title: 'Star Blaster',
    emoji: '🚀',
    tag: 'Play now',
    path: '/games/star-blaster',
    blurb: 'Wave after wave of arcade space combat.',
    goal: 'Survive wave after wave of enemies. Shoot them down for points before they reach you.',
    controls: 'Left/right or stick to move · ✕ or R2 to fire',
  },
  {
    id: 'pong',
    title: 'Pong',
    emoji: '🏓',
    tag: 'Play now',
    path: '/games/pong',
    blurb: 'The original. First to seven against the CPU.',
    goal: 'Beat the CPU to 7 points. Miss the ball and they score.',
    controls: 'Up/Down or left stick to move your paddle',
  },
  {
    id: 'breakout',
    title: 'Breakout',
    emoji: '🧱',
    tag: 'Play now',
    path: '/games/breakout',
    blurb: 'Bounce, break every brick, don’t drop the ball.',
    goal: 'Break every brick without letting the ball fall past your paddle.',
    controls: 'Left/right or stick to move the paddle',
  },
  {
    id: 'asteroids',
    title: 'Asteroids',
    emoji: '☄️',
    tag: 'Play now',
    path: '/games/asteroids',
    blurb: 'Rotate, thrust, blast rocks into smaller rocks.',
    goal: 'Blast every asteroid into smaller pieces (then blast those too) without getting hit.',
    controls: 'Left/right to turn · Up or R2 to thrust · ✕ to fire',
  },
  {
    id: 'flappy',
    title: 'Flappy',
    emoji: '🐤',
    tag: 'Play now',
    path: '/games/flappy',
    blurb: 'One button. Infinite regret. How far can you get?',
    goal: 'Flap through the gaps between pipes. One hit and it’s over — beat your best score.',
    controls: '✕ or Up to flap (or just tap the screen)',
  },
  {
    id: 'simon',
    title: 'Simon',
    emoji: '🧠',
    tag: 'Play now',
    path: '/games/simon',
    blurb: 'Watch the pattern, repeat it, and hope your memory holds.',
    goal: 'Watch the growing pattern of lights, then repeat it back exactly. One mistake ends the round.',
    controls: 'D-pad / arrow keys to repeat the pattern',
  },
  {
    id: 'frogger',
    title: 'Frogger',
    emoji: '🐸',
    tag: 'Play now',
    path: '/games/frogger',
    blurb: 'Cross the traffic. Don’t become a hood ornament.',
    goal: 'Cross the road (and whatever else is in the way) to reach the other side and score.',
    controls: 'D-pad / left stick / arrow keys / WASD to move',
  },
  {
    id: 'whack',
    title: 'Whack-a-Mole',
    emoji: '🔨',
    tag: 'Play now',
    path: '/games/whack-a-mole',
    blurb: '30 seconds. Fast hands only.',
    goal: 'Whack as many moles as you can before the 30-second clock runs out.',
    controls: 'D-pad / stick to move the cursor · ✕ to whack',
  },
  {
    id: 'ttt',
    title: 'Tic-Tac-Toe',
    emoji: '⭕',
    tag: 'Play now',
    path: '/games/tic-tac-toe',
    blurb: 'Simple, fast, and the CPU actually tries to win.',
    goal: 'Get three in a row before the CPU does.',
    controls: 'D-pad to move the cursor · ✕ to place',
  },
  {
    id: '2048',
    title: '2048',
    emoji: '🔢',
    tag: 'Play now',
    path: '/games/2048',
    blurb: 'Slide, merge, chase the big tile.',
    goal: 'Slide tiles to merge matching numbers. Chase the highest tile you can before the board fills up.',
    controls: 'D-pad / stick / arrow keys / WASD to slide the tiles',
  },
  {
    id: 'memory',
    title: 'Memory Match',
    emoji: '🃏',
    tag: 'Play now',
    path: '/games/memory-match',
    blurb: 'Flip two, find the pairs, beat your best move count.',
    goal: 'Flip two cards at a time to find every matching pair, in as few moves as possible.',
    controls: 'D-pad to move the cursor · ✕ to flip a card',
    // Fewer moves is the better result — see Leaderboard's `ascending` prop.
    rankAscending: true,
    format: formatMoves,
  },
];

// A game's slug as stored in ArcadeScore.gameId (and used in its route) is
// the last segment of `path`, e.g. '/games/drift-racer' -> 'drift-racer' —
// not the same as this catalog's own `id` (kept short for React keys).
export function gameBySlug(slug) {
  return GAMES.find((g) => g.path === `/games/${slug}`);
}
